[package]
name = "live_server"
version = "0.1.0"
edition = "2024"

[dependencies]
ray_tracing_challenge_rs = { path = ".." }
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"
tower-http = { version = "0.6", features = ["cors", "fs"] }
async-stream = "0.3.6"
